name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit test
      run: make test
    - name: Unit test with nopic
      run: make test-nopic
    - name: Test for self hosting
      run: make test-stage2
    - name: Check a diff between stage2 and stage3 compiler
      run: make test-stage3
