name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: unit test
      run: make test
    - name: test for self hosting
      run: make test-stage2
    - name: check a diff between stage2 and stage3 compiler
      run: make test-stage3
