name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test tokenize
      run: |
          make
          cd tests
          ../711cc -I. -E tests.c
    - name: Test for compile
      run: make test
    - name: Test with nopic
      run: make test-nopic
    - name: Test for self hosting
      run: make test-stage2
    - name: Check a diff between stage2 and stage3 compiler
      run: make test-stage3
    - name: Test RISC-V-64 target
      run: make test-riscv
